import type {
  Env,
  Gallery,
  InlineKeyboardMarkup,
  PanelEntry,
  SeriesEntry,
  SeriesFile,
} from "./types";
import { parseIssue, slugify } from "./caption";
import { formatIssue, mutateJsonFile, readGalleryJson, readJsonFile } from "./github";

/**
 * A rateable thing. `series` is the series the target belongs to — the target
 * itself when `type` is "series" — so `/rate_series` can walk up from an issue
 * and a write echo can quote both aggregates without a second resolve.
 */
export interface RatingTarget {
  type: "issue" | "series";
  id: string;
  label: string;
  series: { id: string; label: string };
}

export interface Aggregate {
  avg: number | null;
  count: number;
}

/** One person's mark on one target. `uid` is the identity key — see `userKey`. */
export interface RatingRow {
  uid: string;
  user: string;
  score: number | null;
  review: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface TargetRatings {
  label: string;
  avg: number | null;
  count: number;
  ratings: RatingRow[];
}

export interface RatingsIndex {
  generatedAt: string;
  targets: Record<string, TargetRatings>;
}

export const RATINGS_PATH = "public/data/ratings.json";

const MAX_REVIEW_CHARS = 1000;
const CACHE_ORIGIN = "https://cache.comic-snaps.internal";
const SOURCE_CACHE_SECONDS = 60;

// ---------------------------------------------------------------------------
// Cached source reads
// ---------------------------------------------------------------------------

/**
 * Cache a derived value in the edge cache for a minute. Resolving a panel
 * number or a series name costs a GitHub read; the tap path (§1.1) never needs
 * one, but the `/rate` path would pay it on every command without this.
 */
async function cachedJson<T>(key: string, load: () => Promise<T>): Promise<T> {
  const req = new Request(`${CACHE_ORIGIN}/${key}`);
  const cache = caches.default;

  const hit = await cache.match(req);
  if (hit) return (await hit.json()) as T;

  const data = await load();
  await cache.put(
    req,
    new Response(JSON.stringify(data), {
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": `max-age=${SOURCE_CACHE_SECONDS}`,
      },
    })
  );
  return data;
}

async function loadGallery(env: Env): Promise<Gallery> {
  return cachedJson("gallery", async () => (await readGalleryJson(env)).gallery);
}

async function loadSeries(env: Env): Promise<SeriesEntry[]> {
  return cachedJson("series", async () => {
    const { data } = await readJsonFile<SeriesFile>(env, "public/data/series.json");
    return data?.series ?? [];
  });
}

// ---------------------------------------------------------------------------
// Target ids
// ---------------------------------------------------------------------------

/**
 * `{series-slug}-{issue-slug}` — the same transform a panel id is built from
 * (`index.ts`), so two panels from one issue collapse onto one target.
 * Deliberately not keyed off `issues.json`: that file only carries
 * Metron-sourced issues, and ratings have to stand alone (§2.1).
 */
export function issueTargetId(slug: string, issue: number | string): string {
  return `${slug}-${slugify(String(issue))}`;
}

export function issueLabel(title: string, issue: number | string): string {
  return `${title} ${formatIssue(issue)}`;
}

/** The rating target for a gallery panel — the issue it came from, not the panel. */
export function targetForPanel(panel: PanelEntry, forceSeries: boolean): RatingTarget {
  const series = { id: panel.slug, label: panel.title };
  if (forceSeries) {
    return { type: "series", id: series.id, label: series.label, series };
  }
  return {
    type: "issue",
    id: issueTargetId(panel.slug, panel.issue),
    label: issueLabel(panel.title, panel.issue),
    series,
  };
}

// ---------------------------------------------------------------------------
// Reference grammar (§1.6)
// ---------------------------------------------------------------------------

interface SeriesInfo {
  id: string;
  name: string;
  aliases: string[];
}

function normalize(s: string): string {
  return s.trim().toLowerCase();
}

/**
 * Everything that can be named as a series: the metadata records plus every
 * slug the gallery actually uses. The gallery half matters because
 * `series.json` is generated by a separate metadata pass that may not have run
 * for a freshly posted series.
 */
async function seriesIndex(env: Env): Promise<SeriesInfo[]> {
  const [gallery, series] = await Promise.all([loadGallery(env), loadSeries(env)]);

  const byId = new Map<string, SeriesInfo>();
  for (const p of gallery.panels) {
    if (!p.slug) continue;
    if (!byId.has(p.slug)) byId.set(p.slug, { id: p.slug, name: p.title, aliases: [] });
  }
  for (const s of series) {
    const existing = byId.get(s.id);
    const aliases = (s.aliases ?? []).filter((a): a is string => !!a);
    if (existing) {
      existing.name = s.name || existing.name;
      existing.aliases = aliases;
    } else {
      byId.set(s.id, { id: s.id, name: s.name, aliases });
    }
  }
  return Array.from(byId.values());
}

function matchSeries(list: SeriesInfo[], ref: string): SeriesInfo | undefined {
  const r = normalize(ref);
  if (!r) return undefined;
  return (
    list.find((s) => normalize(s.id) === r) ??
    list.find((s) => normalize(s.name) === r) ??
    list.find((s) => s.aliases.some((a) => normalize(a) === r))
  );
}

/** Near misses for a reference that matched nothing, so recovery can be a tap. */
function seriesCandidates(list: SeriesInfo[], ref: string, limit = 6): SeriesInfo[] {
  const r = normalize(ref);
  if (!r) return [];
  const scored = list
    .map((s) => {
      const name = normalize(s.name);
      const id = normalize(s.id);
      if (name.startsWith(r) || id.startsWith(r)) return { s, rank: 0 };
      if (name.includes(r) || id.includes(r)) return { s, rank: 1 };
      if (r.includes(name) && name.length > 2) return { s, rank: 2 };
      return null;
    })
    .filter((x): x is { s: SeriesInfo; rank: number } => x !== null)
    .sort((a, b) => a.rank - b.rank || a.s.name.localeCompare(b.s.name));
  return scored.slice(0, limit).map((x) => x.s);
}

function seriesTarget(s: SeriesInfo): RatingTarget {
  return {
    type: "series",
    id: s.id,
    label: s.name,
    series: { id: s.id, label: s.name },
  };
}

function issueTarget(s: SeriesInfo, issueRef: string): RatingTarget {
  const issue = parseIssue(issueRef);
  return {
    type: "issue",
    id: issueTargetId(s.id, issue),
    label: issueLabel(s.name, issue),
    series: { id: s.id, label: s.name },
  };
}

export interface ResolveOpts {
  /** `/rate_series` — every reference lands on the series. */
  forceSeries?: boolean;
  /** Target of the message this command replied to, if any. */
  replyTarget?: RatingTarget | null;
}

export type ResolveResult =
  | { ok: true; target: RatingTarget }
  | { ok: false; message: string; candidates: RatingTarget[] };

function fail(message: string, candidates: SeriesInfo[] = []): ResolveResult {
  return { ok: false, message, candidates: candidates.map(seriesTarget) };
}

/** Narrow a resolved target to its series when the command forces it. */
function applyForce(target: RatingTarget, forceSeries: boolean): RatingTarget {
  if (!forceSeries || target.type === "series") return target;
  return {
    type: "series",
    id: target.series.id,
    label: target.series.label,
    series: target.series,
  };
}

/**
 * The one reference resolver every rating command shares (§1.6). Steps are
 * tried in the documented order — in particular the whole string is tried as a
 * series name *before* a trailing number is split off, so `2000 AD` and `100%`
 * resolve as series rather than as a series plus an issue.
 */
export async function resolveTarget(
  env: Env,
  ref: string,
  opts: ResolveOpts = {}
): Promise<ResolveResult> {
  const force = opts.forceSeries ?? false;
  const trimmed = ref.trim();

  // 1. Explicit prefix — the escape hatch for anything the heuristics misread.
  const prefixed = trimmed.match(/^(panel|series|issue):\s*(.+)$/i);
  if (prefixed) {
    const kind = prefixed[1].toLowerCase();
    const rest = prefixed[2].trim();

    if (kind === "panel") {
      if (!/^\d+$/.test(rest)) return fail(`"${rest}" isn't a panel number.`);
      const panel = await findPanel(env, parseInt(rest, 10));
      if (!panel) return fail(`No panel found with ID ${rest}.`);
      return { ok: true, target: targetForPanel(panel, force) };
    }

    const list = await seriesIndex(env);
    if (kind === "series") {
      const s = matchSeries(list, rest);
      if (!s) return fail(`No series found matching "${rest}".`, seriesCandidates(list, rest));
      return { ok: true, target: seriesTarget(s) };
    }

    // issue:saga-4 — a raw target id. Label it from a panel when one exists.
    const gallery = await loadGallery(env);
    const panel = gallery.panels.find(
      (p) => issueTargetId(p.slug, p.issue) === normalize(rest)
    );
    if (panel) return { ok: true, target: targetForPanel(panel, force) };
    const owner = list.find((s) => normalize(rest).startsWith(`${normalize(s.id)}-`));
    const series = owner
      ? { id: owner.id, label: owner.name }
      : { id: normalize(rest), label: rest };
    if (force) {
      return { ok: true, target: { type: "series", id: series.id, label: series.label, series } };
    }
    return { ok: true, target: { type: "issue", id: normalize(rest), label: rest, series } };
  }

  // 2. Empty reference in a reply — the replied-to message's target.
  if (!trimmed) {
    if (opts.replyTarget) {
      return { ok: true, target: applyForce(opts.replyTarget, force) };
    }
    return fail("Which one? Reply to a panel, or name it: /rate Saga #4 8");
  }

  // 3. Bare digits — a panel `seq`. Takes precedence over a series *named*
  //    with digits; `series:100` disambiguates. Falls through when no panel
  //    carries that number, so `/rate 100 9` still reaches the series 100%.
  if (/^\d+$/.test(trimmed)) {
    const panel = await findPanel(env, parseInt(trimmed, 10));
    if (panel) return { ok: true, target: targetForPanel(panel, force) };
  }

  const list = await seriesIndex(env);

  // 4. `#` marker — everything after it is the issue, verbatim, so
  //    `Hellboy #Annual 2` works. A failing head is a real error, not a reason
  //    to reinterpret the string.
  const hashIdx = trimmed.indexOf("#");
  if (hashIdx > 0) {
    const head = trimmed.slice(0, hashIdx).trim();
    const issueRef = trimmed.slice(hashIdx + 1).trim();
    if (issueRef) {
      const s = matchSeries(list, head);
      if (!s) return fail(`No series found matching "${head}".`, seriesCandidates(list, head));
      return { ok: true, target: applyForce(issueTarget(s, issueRef), force) };
    }
  }

  // 5. The whole string as a series name.
  const whole = matchSeries(list, trimmed);
  if (whole) return { ok: true, target: seriesTarget(whole) };

  // 6. Trailing token as the issue.
  const split = trimmed.match(/^(.*\S)\s+(\S+)$/);
  if (split) {
    const s = matchSeries(list, split[1]);
    if (s) return { ok: true, target: applyForce(issueTarget(s, split[2]), force) };
  }

  return fail(`No series or panel found matching "${trimmed}".`, seriesCandidates(list, trimmed));
}

async function findPanel(env: Env, seq: number): Promise<PanelEntry | null> {
  const gallery = await loadGallery(env);
  return gallery.panels.find((p) => p.seq === seq) ?? null;
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

export type RateArgs =
  | { ok: true; ref: string; score: number | null; review: string | null }
  | { ok: false; message: string };

/**
 * Split a rating command's argument into reference, score and review.
 *
 * The review is everything after `//`. In what's left, the *last* whitespace
 * token is the score — that's what makes `/rate Saga 9` the series at 9 rather
 * than issue 9 of Saga. `8` and `8/10` are both accepted.
 */
export function parseRateArgs(raw: string): RateArgs {
  const sepIdx = raw.indexOf("//");
  const head = (sepIdx === -1 ? raw : raw.slice(0, sepIdx)).trim();
  const reviewRaw = sepIdx === -1 ? null : raw.slice(sepIdx + 2).trim();
  const review = reviewRaw ? reviewRaw : null;

  if (review && review.length > MAX_REVIEW_CHARS) {
    return {
      ok: false,
      message: `That review is ${review.length} characters — the cap is ${MAX_REVIEW_CHARS}.`,
    };
  }

  const tokens = head.split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return { ok: true, ref: "", score: null, review };

  const last = tokens[tokens.length - 1];
  const scoreMatch = last.match(/^(\d{1,3})(?:\/10)?$/);
  if (!scoreMatch) return { ok: true, ref: head, score: null, review };

  const score = parseInt(scoreMatch[1], 10);
  if (score < 1 || score > 10) {
    // A lone out-of-range number is far more likely a reference with the score
    // left off (`/rate 247`) than a bad score, so let the caller say so.
    if (tokens.length === 1) return { ok: true, ref: head, score: null, review };
    return { ok: false, message: "Scores run 1–10." };
  }

  return { ok: true, ref: tokens.slice(0, -1).join(" "), score, review };
}

// ---------------------------------------------------------------------------
// Store — public/data/ratings.json, committed to the repo like every other
// data file. See docs/ratings-plan.md §3.
// ---------------------------------------------------------------------------

function emptyIndex(): RatingsIndex {
  return { generatedAt: new Date().toISOString(), targets: {} };
}

export function targetKey(type: "issue" | "series", id: string): string {
  return `${type}:${id}`;
}

/**
 * A stable, opaque identity for a rater. The file is published, so the raw
 * Telegram id can't go in it — but re-rating has to find the same row, and a
 * first name is neither stable nor unique. Salted, so the short digest can't be
 * walked back to an id by brute force.
 */
export async function userKey(env: Env, telegramId: number): Promise<string> {
  const salt = env.RATINGS_SALT ?? env.WEBHOOK_SECRET ?? "comic-snaps";
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(`${salt}:${telegramId}`)
  );
  return Array.from(new Uint8Array(digest).slice(0, 6))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function round1(n: number): number {
  return Math.round(n * 10) / 10;
}

/**
 * Recompute a target's average from its rows. Score and review are independent,
 * so a row carrying only a review contributes nothing to the mean — and the
 * count is published next to the average rather than hidden behind a prior,
 * because at this group size the count *is* the caveat (§8).
 */
function reaggregate(entry: TargetRatings): void {
  const scores = entry.ratings.map((r) => r.score).filter((v): v is number => v !== null);
  entry.count = scores.length;
  entry.avg = scores.length ? round1(scores.reduce((a, b) => a + b, 0) / scores.length) : null;
  entry.ratings.sort(
    (a, b) => (b.score ?? -1) - (a.score ?? -1) || b.updatedAt.localeCompare(a.updatedAt)
  );
}

export interface UpsertResult {
  previous: { score: number | null; review: string | null } | null;
  current: { score: number | null; review: string | null };
  removed: boolean;
  target: Aggregate;
  series: Aggregate;
  label: string;
}

export async function readRatings(env: Env): Promise<RatingsIndex> {
  const { data } = await readJsonFile<RatingsIndex>(env, RATINGS_PATH);
  return data ?? emptyIndex();
}

/**
 * Add or change one person's rating, then commit the file. A score alone leaves
 * an existing review untouched and a review alone leaves the score untouched
 * (§1.2) — that's the only merge rule, and it's why score and review share one
 * row rather than being two entities. A row left with neither is dropped.
 */
export async function upsertRating(
  env: Env,
  target: RatingTarget,
  user: { id: number; name: string },
  score: number | null,
  review: string | null
): Promise<UpsertResult> {
  const uid = await userKey(env, user.id);
  const now = new Date().toISOString();
  const key = targetKey(target.type, target.id);
  const seriesKey = targetKey("series", target.series.id);

  return mutateJsonFile<RatingsIndex, UpsertResult>(env, RATINGS_PATH, emptyIndex, (index) => {
    index.generatedAt = now;
    const entry = (index.targets[key] ??= {
      label: target.label,
      avg: null,
      count: 0,
      ratings: [],
    });
    entry.label = target.label;

    const existing = entry.ratings.find((r) => r.uid === uid) ?? null;
    const previous = existing ? { score: existing.score, review: existing.review } : null;

    const row: RatingRow = existing ?? {
      uid,
      user: user.name,
      score: null,
      review: null,
      createdAt: now,
      updatedAt: now,
    };
    if (!existing) entry.ratings.push(row);

    row.user = user.name;
    if (score !== null) row.score = score;
    if (review !== null) row.review = review;
    row.updatedAt = now;

    let removed = false;
    if (row.score === null && row.review === null) {
      entry.ratings = entry.ratings.filter((r) => r.uid !== uid);
      removed = true;
    }

    reaggregate(entry);
    const label = entry.label;
    const aggregate: Aggregate = { avg: entry.avg, count: entry.count };
    if (entry.ratings.length === 0) delete index.targets[key];

    const seriesEntry = index.targets[seriesKey];
    return {
      result: {
        previous,
        current: { score: row.score, review: row.review },
        removed,
        target: aggregate,
        series: seriesEntry
          ? { avg: seriesEntry.avg, count: seriesEntry.count }
          : { avg: null, count: 0 },
        label,
      },
      message: `Rate ${target.label}: ${user.name} ${score ?? "review"}`,
    };
  });
}

export function aggregateFrom(
  index: RatingsIndex,
  type: "issue" | "series",
  id: string
): Aggregate {
  const entry = index.targets[targetKey(type, id)];
  return entry ? { avg: entry.avg, count: entry.count } : { avg: null, count: 0 };
}

export function ratingsFrom(
  index: RatingsIndex,
  type: "issue" | "series",
  id: string
): RatingRow[] {
  return index.targets[targetKey(type, id)]?.ratings ?? [];
}

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

/**
 * The 2x5 score pad, attached to `/rate` replies only — panel posts stay plain,
 * since rating is the occasional case, not the default one.
 *
 * `callback_data` has a 64-byte budget and carries the target id outright; the
 * longest id in the gallery today comes to 57. The `r1` prefix lets the format
 * change without stale buttons misfiring. Returns undefined when an id won't
 * fit, in which case the pad is simply omitted and `/rate` still works.
 */
export function ratingKeyboard(handle: string): InlineKeyboardMarkup | undefined {
  if (`r1|${handle}|10`.length > 64) return undefined;
  const row = (from: number) =>
    Array.from({ length: 5 }, (_, i) => {
      const score = from + i;
      return { text: String(score), callback_data: `r1|${handle}|${score}` };
    });
  return { inline_keyboard: [row(1), row(6)] };
}

/** `i<id>` / `s<id>` — the target itself, since ids fit the 64-byte budget. */
export function targetHandle(target: RatingTarget): string {
  return `${target.type === "issue" ? "i" : "s"}${target.id}`;
}

export function parseCallbackData(data: string): { handle: string; score: number } | null {
  const m = data.match(/^r1\|(.+)\|(\d{1,2})$/);
  if (!m) return null;
  const score = parseInt(m[2], 10);
  if (score < 1 || score > 10) return null;
  return { handle: m[1], score };
}

/** Turn a callback handle back into a full target, labelled from the gallery. */
export async function targetFromHandle(env: Env, handle: string): Promise<RatingTarget | null> {
  const kind = handle[0];
  const rest = handle.slice(1);
  if (!rest) return null;
  if (kind !== "i" && kind !== "s") return null;

  const list = await seriesIndex(env);
  if (kind === "s") {
    const owner = list.find((x) => x.id === rest);
    const label = owner?.name ?? rest;
    return { type: "series", id: rest, label, series: { id: rest, label } };
  }

  const owner = list.find((x) => rest.startsWith(`${x.id}-`));
  const series = owner ? { id: owner.id, label: owner.name } : { id: rest, label: rest };
  // Re-derive the issue's display label from a panel when the gallery has one.
  const gallery = await loadGallery(env);
  const panel = gallery.panels.find((p) => issueTargetId(p.slug, p.issue) === rest);
  return {
    type: "issue",
    id: rest,
    label: panel ? issueLabel(panel.title, panel.issue) : rest,
    series,
  };
}

export function formatAggregate(agg: Aggregate): string {
  if (agg.count === 0) return "no ratings yet";
  return `${agg.avg?.toFixed(1)} from ${agg.count}`;
}

/** `Saga #4 - 8.0 from 2 - Jacob 8 - Sam 8` */
export function tallyText(label: string, rows: RatingRow[], agg: Aggregate): string {
  const names = rows
    .filter((r) => r.score !== null)
    .map((r) => `${r.user} ${r.score}`)
    .join(" · ");
  const head = `${label} — ${formatAggregate(agg)}`;
  return names ? `${head} · ${names}` : head;
}

/**
 * Drop the cached gallery/series reads. Called after any write to the repo, so
 * a panel posted a moment ago is immediately rateable by its ID.
 */
export async function invalidateSourceCache(): Promise<void> {
  await Promise.all([
    caches.default.delete(new Request(`${CACHE_ORIGIN}/gallery`)),
    caches.default.delete(new Request(`${CACHE_ORIGIN}/series`)),
  ]);
}
